sudo: false
dist: xenial
language: go
go:
  - master

install:
  - go get github.com/gohugoio/hugo

before_script:
  - rm -rf public 2> /dev/null

script:
  - hugo
  - echo "hankaibo" > public/CNAME

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  verbose: true
  keep-history: true
  local_dir: public
  target_branch: master
  on:
    branch: code
