name: Deploy Hugo to Github Pages CI

on:
  push:
    branches: [ code ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Hugo setup
        uses: peaceiris/actions-hugo@v2.4.10
        with:
          # The Hugo version to download (if necessary) and use. Example: 0.58.2
          hugo-version: 0.69.0
          # Download (if necessary) and use Hugo extended version. Example: true
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ThinkPad }}
          publish_dir: ./public
